### ISSUE TITLE
bare minimum cni configuration

### ISSUE THREAD

**Issue by avoidik** [Mirantis/cri-dockerd#164]
hello all,

on a clean install I have got a blank cni configuration directory, there were no files in the `/etc/cni/net.d/` at all, please suggest what is the bare minimum cni configuration I may use to bootstrap my kubernetes cluster using kubeadm?

without the cni configuration I'm unable to complete installation with `Container runtime network not ready: cni config uninitialized` error, I assume there's something missing in packages for aarch64 cpu

```terminal
$ cri-dockerd --version
cri-dockerd 0.3.1 (7e528b98)
```

```terminal
$ docker version --format '{{.Server.Version}}'
23.0.1
```

```terminal
$ dpkg --print-architecture 
arm64
```

```terminal
$ uname -p
aarch64
```

```terminal
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

```terminal
$ containerd --version
containerd containerd.io 1.6.16 31aa4358a36870b21a992d3ad2bef29e1d693bec
```

**Comment by afbjorklund** [comment]
> I assume there's something missing in packages for aarch64 cpu

No, configuring CRI and CNI is "left as an exercise for the reader" (in k8s)

**Comment by avoidik** [comment]
Thanks @afbjorklund I thought something was wrong with the CRI

**Comment by afbjorklund** [comment]
You can set up a basic "bridge" network, if you want something simple.

```yaml
{
  "cniVersion": "0.3.1",
  "name": "docker-net",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni0",
      "isGateway": true,
      "ipMasq": true,
      "hairpinMode": true,
      "ipam": {
        "type": "host-local",
        "ranges": [
          [{
            "subnet": "10.10.0.0/16"
          }]
        ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true}
    }
  ]
}
```

Or use flannel: https://github.com/flannel-io/flannel#deploying-flannel-manually
