### ISSUE TITLE
Migrate from the obsolete SeccompProfilePath 

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/cri-dockerd#198]
`GetSeccompProfilePath()` is deprecated but still being used by `cri-dockerd`. A [recent change to `cri-tools`](https://github.com/kubernetes-sigs/cri-tools/pull/1181) migrates the tests from using the old method and instead switches to the new method. This causes our integration and e2e tests to fail due to still using the old method. 

This issue is to make the changes to support the new method of retrieving the seccomp profile.

**Note**
As a temporary work around (this is causing all builds to fail), we can pin the `cri-tools` to the commit before the change using 
```
      - name: Check out cri-tools
        uses: actions/checkout@v2
        with:
          repository: kubernetes-sigs/cri-tools
          path: src/sigs.k8s.io/cri-tools
          ref: e3c99451faee42de2fcf4568bdd81be8bb29e40f
```
as I've done in https://github.com/Mirantis/cri-dockerd/pull/197. This will let us move on with other changes until we have the fix in for this.
